# Generated by Django 3.2.3 on 2021-06-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('correoElectronico', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('contrasenia', models.CharField(max_length=100, verbose_name='contraseña')),
                ('confirmarcontrasenia', models.CharField(max_length=100, verbose_name='Confirmar contraseña')),
            ],
        ),
    ]
